[NEOS-1215] Add github action that fails if go mod tidy results in git changes #2223

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -76,3 +76,27 @@ jobs:
         uses: codecov/codecov-action@v4
         env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+
+  go-mod-tidy-check:
+    name: go-mod-tidy-check
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version-file: go.mod
+          cache-dependency-path: go.sum
+
+      - name: Run go mod tidy
+        run: go mod tidy
+
+      - name: Check for changes in go.mod and go.sum
+        run: |
+          if [ -n "$(git status --porcelain go.mod go.sum)" ]; then
+            echo "Error: go.mod and/or go.sum have changes after running 'go mod tidy'"
+            echo "Please run 'go mod tidy' and commit the changes."
+            exit 1
+          fi
